### PR TITLE
Adding CaR doc reference to readme file

### PR DESCRIPTION
**Pull request by pskopek**

### CODE REVIEW

**Comment by darranl** [comment]
Peter, you have accidentally pushed your topic branch to the upstream repo - can you correct and send the pull request from your repo?

**Comment by pskopek** [comment]
hm, I edited the file directly using web interface. One cannot select where the branch will be created.
I will send proper PR.

**Comment by darranl** [comment]
If you navigated to the file in your own repo I would expect that would trigger creating the branch there.

**Comment by pskopek** [comment]
I will try next time ;-)

**Pull request closed without merging**
