### PR TITLE
Resolves #53

### LINKED ISSUE #53: Add a temporary 'authenticate' operation so that authentication can be tested without end to end being available,

### PR DESCRIPTION
**Pull request by pedroigor**

### CODE REVIEW

**Comment by pedroigor** [comment]
Before using this, make sure you have https://github.com/wildfly/wildfly-core/pull/825 merged into your wildfly-core branch.

**Comment by darranl** [comment]
Looks good but can you please just update the commit message so it says 'Resolves #53' instead of referencing ELY-213 then I will go ahead an update the projects and merge.

**Comment by sguilhen** [comment]
Would be good to merge the wildfly-core commit into the incubator branch to avoid this extra step when setting things up.

**Comment by darranl** [comment]
Am in the process of rebasing both forks so the commit will be there.

**Comment by darranl** [comment]
Merged

**Pull request closed without merging**
