### PR TITLE
[WFLY-7176] x500-attribute-principal-decoder - names instead of OIDs

### PR DESCRIPTION
**Pull request by honza889**
Depends on https://github.com/wildfly-security/wildfly-elytron/pull/550
https://issues.jboss.org/browse/WFLY-7176

Note: OID+ATTRIBUTE_NAME should be set as require when will be WFCORE-1556 resolved:
http://wildfly-development.1055759.n5.nabble.com/Fixing-handling-of-required-attributes-with-alternatives-td5717450.html

UPDATE: or do you think it woul be better one attribute "attribute", which would combine OID+ATTRIBUTE_NAME ?

### CODE REVIEW

**Comment by honza889** [comment]
Reworked: loading from properties file with categories

**Comment by honza889** [comment]
Rebased.

**Comment by darranl** [comment]
Looks good, just requires a rebase.

**Comment by honza889** [comment]
Should be ok now. (with SNAPSHOT of elytron)

**Pull request merged**
