### PR TITLE
[WFLY-7154] poor description of session-timeout,maximum-session-cache-size attributes.

### PR DESCRIPTION
**Pull request by ivassile**
WildFly: https://issues.jboss.org/browse/WFLY-7154

### CODE REVIEW

**Comment by ivassile** [comment]
@darranl : I chose to implement [1]. Created ELY-654 [2] and submitted PR [3]. 
Q: Do we need to add a note about this change in Elytron Subsystem (wildfly-elytron_1_0.xsd) or current change with description is enough?
Q: PR [3] converts the value to '0' in SSLContextBuilder. Do we also need to convert it in AbstractDelegatingSSLSessionContext?
[1]
Personally I prefer the approach that minimises the chance a user will have an error to correct so prefer converting negatives to '0' within Elytron and ensure the descriptions in the schema and for the resources are appropriate.
[2] https://issues.jboss.org/browse/ELY-654
[3] https://github.com/wildfly-security/wildfly-elytron/pull/505

**Comment by ivassile** [comment]
This is now fixed and ready to be merged.

**Comment by darranl** [comment]
As https://github.com/wildfly-security/wildfly-elytron/pull/505 has been merged I think this one can be closed?  i.e. we don't need the schema adjusted to use a non-negative integer?

**Comment by ivassile** [comment]
I've removed the schema changes to use a non-negative integer, but I think we need to keep the description "The default value zero means there is no limit."

**Pull request merged**
