### PR TITLE
[WFLY-7153] ssl-context - provider-loader, provider

### PR DESCRIPTION
**Pull request by honza889**
https://issues.jboss.org/browse/WFLY-7153

### CODE REVIEW

**Comment by honza889** [comment]
[HALT] the security-domain is used, dont remove

**Comment by darranl** [comment]
I am placing this one on hold for the moment so we can discuss how we want to handle this.  We do still need to completely redesign the provider-loader resources that may make this redundant.

Also as a general comment, we don't really want implementation code appearing in the subsystem more than is absolutely necessary if we do want to add support for different types of filtering that should really be implemented within Elytron with the subsystem just calling the appropriate API to enable that filtering.

**Comment by honza889** [comment]
TODO: check if PropertiesAttributeDefinition could be used

**Comment by honza889** [comment]
Rebased.

**Pull request merged**
