### PR TITLE
[WFLY-7285] Elytron - inconsistency between DMR and XSD representation of simple-permission-mapper

### PR DESCRIPTION
**Pull request by ivassile**
Elytron Subsystem: https://issues.jboss.org/browse/WFLY-7285

### CODE REVIEW

**Comment by darranl** [comment]
@honza889 Also on this one could you please double check the modified constraints match the constraints required within Elytron.

**Comment by honza889** [comment]
I dont think we need to prevent creating blank simple-permission-mapper or blank permissions...

**Comment by ivassile** [comment]
Implemented the requested changes: "Mapper without mappings and mapping without permissions should not be a problem."

**Comment by honza889** [comment]
+1

**Pull request merged**
