### PR TITLE
Add default permissions for EJB and transactions

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
Small problem, this seems to break *everything*.  I guess because the new permission classes I've added aren't present in this code base.  Or wildfly-core for that matter.

**Comment by dmlloyd** [comment]
I think unresolved permissions should be logged and ignored.

**Comment by dmlloyd** [comment]
I take it back.  Upstream is already completely broken without any intervention on my part. I'm going to set my PR against an earlier version.

**Comment by dmlloyd** [comment]
Tried with latest snapshot, no dice.  I leave it up to @darranl to sort out I guess :)

**Comment by darranl** [comment]
I will look but that is weird - you have added it in the same supplement as the batch permission so should only be used on a full WildFly.

**Pull request merged**
